services:
  app:
    build: .
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - data:/usr/src/app/data
      - logs:/usr/src/app/logs

volumes:
  data:
  logs: